"""empty message

Revision ID: fa2c20383e0c
Revises: 762402052503
Create Date: 2021-04-12 03:25:17.816200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2c20383e0c'
down_revision = '762402052503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.String(), nullable=False),
    sa.Column('birth_year', sa.String(), nullable=False),
    sa.Column('eye_color', sa.String(), nullable=False),
    sa.Column('films', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('hair_color', sa.String(), nullable=False),
    sa.Column('height', sa.String(), nullable=False),
    sa.Column('homeworld', sa.String(), nullable=False),
    sa.Column('mass', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('skin_color', sa.String(), nullable=False),
    sa.Column('created', sa.String(), nullable=False),
    sa.Column('edited', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('starships', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('vehicles', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fav_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'people_id', 'user_id')
    )
    op.create_table('fav_planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('climate', sa.String(), nullable=False),
    sa.Column('created', sa.String(), nullable=False),
    sa.Column('diameter', sa.String(), nullable=False),
    sa.Column('edited', sa.String(), nullable=False),
    sa.Column('films', sa.String(), nullable=False),
    sa.Column('gravity', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('orbital_period', sa.String(), nullable=False),
    sa.Column('population', sa.String(), nullable=False),
    sa.Column('residents', sa.String(), nullable=False),
    sa.Column('rotation_period', sa.String(), nullable=False),
    sa.Column('surface_water', sa.String(), nullable=False),
    sa.Column('terrain', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('starships', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    op.drop_table('fav_planet')
    op.drop_table('fav_people')
    op.drop_table('characters')
    # ### end Alembic commands ###
